# Auto Cursor Agent 配置文件示例
# 复制此文件为 config.yaml 并填入你的实际配置

# AI模型配置
ai_models:
  # OpenAI配置
  openai:
    api_key: "your-openai-api-key-here"
    base_url: "https://api.openai.com/v1"
    model: "gpt-4"
    max_tokens: 4000
    temperature: 0.7
    
  # Claude配置
  claude:
    api_key: "your-claude-api-key-here"
    model: "claude-3-sonnet-20240229"
    max_tokens: 4000
    temperature: 0.7
    
  # 本地模型配置（可选）
  local:
    enabled: false
    endpoint: "http://localhost:11434"
    model: "llama2"

# Cursor配置
cursor:
  # Cursor可执行文件路径
  executable_path: "/Applications/Cursor.app/Contents/MacOS/Cursor"
  # 默认工作空间路径
  workspace_path: "/Users/yourname/projects"
  # 等待时间配置（秒）
  wait_timeout: 30
  command_delay: 2
  
# 监控配置
monitoring:
  # 检查间隔（秒）
  check_interval: 30
  # 文件变化监控
  file_patterns:
    - "*.py"
    - "*.js"
    - "*.ts"
    - "*.jsx"
    - "*.tsx"
    - "*.html"
    - "*.css"
    - "*.json"
  # 忽略的目录
  ignore_patterns:
    - ".git"
    - "node_modules"
    - "__pycache__"
    - ".venv"
  # 质量阈值
  quality_threshold: 0.8
  
# 任务配置
task_management:
  # 最大并发任务数
  max_concurrent_tasks: 3
  # 任务超时时间（分钟）
  task_timeout: 60
  # 重试次数
  max_retries: 3
  
# 日志配置
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name} | {message}"
  rotation: "1 day"
  retention: "7 days"
  
# 开发配置
development:
  # 调试模式
  debug: false
  # 详细日志
  verbose: true
  # 测试模式
  test_mode: false
  
# 通知配置（可选）
notifications:
  # 邮件通知
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: "your-email@gmail.com"
    password: "your-app-password"
    
  # Slack通知
  slack:
    enabled: false
    webhook_url: "your-slack-webhook-url"
    
  # 企业微信通知
  wechat:
    enabled: false
    webhook_url: "your-wechat-webhook-url"

